### ISSUE TITLE
Variable Btoa

### ISSUE THREAD

**Issue by Tilenozz** [tonynguyenit18/paypal-RN-intergration#1]
Good morning.
Actually i clone this project , npm install , and react-native run-anodroid.
The interface appear , but when click on button appear this msg in console : 

ReferenceError: Can't find variable: btoa

I read is Axios trouble. 
Regards

**Comment by tonynguyenit18** [comment]
> Good morning.
> Actually i clone this project , npm install , and react-native run-anodroid.
> The interface appear , but when click on button appear this msg in console :
> 
> ReferenceError: Can't find variable: btoa
> 
> I read is Axios trouble.
> Regards

I have updated the code with btoa bug fixed.
Fore more detail https://github.com/axios/axios/issues/2235
