### ISSUE TITLE
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs 

### ISSUE THREAD

**Issue by Tilenozz** [tonynguyenit18/paypal-RN-intergration#2]
Good evening ,
This repo is working very well , but when uploading in Apple store , this msg is response :

Quote:
We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.
--------------------------------
Have you any suggest on how to resolve ?
Thanks

**Comment by tonynguyenit18** [comment]
> Good evening ,
> This repo is working very well , but when uploading in Apple store , this msg is response :
> 
> Quote:
> We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> ## After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> Have you any suggest on how to resolve ?
> Thanks

Because of using react-native-webview library that using UIWebView (deprecated by Apple).
Check here for more information: https://forums.developer.apple.com/thread/122114
Looking for another webview library or waiting for this library updates and the I can get the dependency updated.

**Comment by Tilenozz** [comment]
Actually on u code , import { WebView } from 'react-native-webview';
So i installed that package

**Comment by tonynguyenit18** [comment]
> Actually on u code , import { WebView } from 'react-native-webview';
> So i installed that package

Sorry for late reply.
UIWebView error is fixed in imported react-native-webview version by its author. Please check orther package.
